# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app/backend

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install any needed packages
RUN npm install

# Copy the rest of the backend source code
COPY backend/ .

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Run index.js when the container launches
CMD [ "node", "index.js" ]
